### ISSUE TITLE
鬼畜歌曲20余首

### ISSUE THREAD

**Issue by Rooootk** [naco-siren/mogicians_manual_public_release#17]
从一个膜蛤群里找到的鬼畜歌曲。
特别推荐：**熙蛤rap二重奏 Gentleman**
[MEGA下载链接](https://mega.nz/#F!E7B1XLLQ!xSVcLLIGm2NxONC3ER4OkQ)

**Comment by naco-siren** [comment]
@Rooootk 已收录部分质量较好的曲子，感谢滋磁。
