### ISSUE TITLE
2个未被收录的靡靡之音（也许是）

### ISSUE THREAD

**Issue by xxX-anonymous-0x3b1b-Xxx** [naco-siren/mogicians_manual_public_release#5]
[音乐库(1).zip](https://github.com/naco-siren/mogicians_manual_public_release/files/1175861/1.zip)
解除压缩凭据：234671
本账号为提交此信息所使用的临时账号，因为主账号与某人的个人信息强连通。反向联系（如果需要）请添加[Telegram账户](https://t.me/aozak)
本帐户的电子邮件地址不受密码保护。建议在安全环境中打开并转录以确保消除潜在的安全威胁。

**Comment by naco-siren** [comment]
@xxX-anonymous-0x3b1b-Xxx 其中一首已在APP中，另一首由于不是基于他老人家原声改编的鬼畜，暂不收录，谢谢资瓷！
