### ISSUE TITLE
段子补充

### ISSUE THREAD

**Issue by xxX-anonymous-0x3b1b-Xxx** [naco-siren/mogicians_manual_public_release#6]
一天，宋徽宗和王希孟在书房作画，宋徽宗画了一幅画让王希孟看。王希孟看到画上守卫手持长枪，铿锵有力，一人在守卫中间骑着马看穿着好像是徽宗，王希孟拿起画来拜读，画平放时很平静，拿起时仿佛守卫在前进，发出霍霍的声音，再看风景部分，这明明就是去年自己陪徽宗游玩九寨沟的场景，于是说了一句：“纸曲笔伏霍音起，疑似圣驾过丽沟。”
#倒背如流

本账号说明信息在 #5 中。

**Comment by naco-siren** [comment]
@xxX-anonymous-0x3b1b-Xxx 谢谢，已收录
